//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCenter.Modal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_ShopOrderEntities : DbContext
    {
        public Db_ShopOrderEntities()
            : base("name=Db_ShopOrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Customer> tbl_Customer { get; set; }
        public DbSet<tbl_Order> tbl_Order { get; set; }
        public DbSet<tbl_OrderDeatail> tbl_OrderDeatail { get; set; }
        public DbSet<tbl_Product> tbl_Product { get; set; }
        public DbSet<tbl_Store> tbl_Store { get; set; }
        public DbSet<tbl_User> tbl_User { get; set; }
        public DbSet<tbl_Register> tbl_Register  {get; set; }
    }
}
