//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCenter.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Store
    {
        public int StoreID { get; set; }
        public int ProductID { get; set; }
        public int Count { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
