//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCenter.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        public tbl_Order()
        {
            this.tbl_OrderDeatail = new HashSet<tbl_OrderDeatail>();
        }
    
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual ICollection<tbl_OrderDeatail> tbl_OrderDeatail { get; set; }
    }
}
