//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCenter.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        public tbl_Customer()
        {
            this.tbl_Order = new HashSet<tbl_Order>();
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Fullname { get; set; }
        public string Mobile { get; set; }
        public string Adress { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<tbl_Order> tbl_Order { get; set; }
    }
}
